
trainingInput:
  hyperparameters:
    goal: MAXIMIZE
    hyperparameterMetricTag: metric_hyp_opt
    maxTrials: 4
    maxParallelTrials: 2
    params:
    - parameterName: learning_rate
      type: DOUBLE
      minValue: 0.001
      maxValue: 0.004
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: layers
      type: DISCRETE
      discreteValues: 
      - 512
      - 1024



    